# Используем базовый образ Ubuntu
FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

# Обновляем список пакетов и устанавливаем пакет nano
RUN apt-get update && \
    apt-get install -y nano && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Установка Python3 и pip
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y cron
RUN apt-get install -y curl
RUN apt-get install -y libpq-dev


# Опционально, устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Опционально, копируем файлы из хост-системы в контейнер
COPY . /app

RUN pip install -r requirements.txt
RUN python3 set_commands.py

EXPOSE 8080

# Опционально, указываем команду по умолчанию, которая будет выполняться при запуске контейнера
CMD ["python3", "main.py"]
